//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UngDung_DiChoThue.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham_Chon
    {
        public int MaKH { get; set; }
        public int MaSP { get; set; }
        public int MaNCC { get; set; }
        public Nullable<System.DateTime> ThoiGianChon { get; set; }
        public string TrangThai { get; set; }
    }
}
